version: "3.3"
services:
    play:
        image: hendrik44/docker-playframework
        hostname: play-test
        container_name: play-test
        command: play run
        ports:
            - 9000:9000
        cap_drop:
            - NET_ADMIN
            - SYS_ADMIN
        read_only: true
        tmpfs:
            - /run
            - /tmp
        volumes:
            - ./src:/app
            # - ~/.ivy2:/root/.ivy2
            
